from abc import ABC, abstractmethod


class RunnerServerABC(ABC):

    async def poll_for_input(self, player_id: str) -> None: ...

    async def receive_action(self, player_id: str, request) -> None: ...

    async def get_actions(self, player_id: str) -> None: ...

    async def push_response(self, player_id: str, request) -> None: ...
