from contracts.runner_server_abc import RunnerServerABC


class CloudRunnerServer(RunnerServerABC):

    def start_server(self) -> None: ...

    def stop_server(self) -> None: ...

    def restart_server(self) -> None: ...

    def get_server_status(self) -> str: ...

    def handle_client_request(self, request: dict) -> dict: ...
