from contracts.runner_client_abc import RunnerClientABC


class CloudRunnerClient(RunnerClientABC):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def connect_to_server(self, server_address: str) -> None: ...

    def disconnect_from_server(self) -> None: ...

    def send_request(self, request: dict) -> dict: ...

    def receive_response(self) -> dict: ...

    def get_client_status(self) -> str: ...
