from game_contracts.runner_client_abc import RunnerClientABC


class CloudRunnerClient(RunnerClientABC):

    def poll_for_server_response(self) -> dict: ...

    def send_action_to_server(self, action) -> None: ...

    def get_games_for_player(self, game_configs) -> list: ...

    def setup_new_game(self, game_configs: dict) -> dict: ...

    def load_existing_game(self, game_configs) -> dict: ...
